version: '2'

services:
  myapp:
    build: ./
    ports:
    - "3000:3000"
    links:
    - database
    volumes:
    - .:/usr/src/app
    depends_on:
    - database
    environment: 
      PORT: 3000
      DB_URL: mongodb://database:27017/practice-stats
  database:
    image: mongo